version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:11.22-bullseye
    environment:
      POSTGRES_USER: /run/secrets/pg_username
      POSTGRES_PASSWORD: /run/secrets/pg_password
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    secrets:
      - pg_username
      - pg_password
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: /run/secrets/pg_username
      DB_PASSWORD: /run/secrets/pg_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8484:8443"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
    secrets:
      - pg_username
      - pg_password
      - keycloak_username
      - keycloak_password
secrets:
  pg_username:
    file: pg_username.txt
  pg_password:
    file: pg_password.txt
  keycloak_username:
    file: keycloak_username.txt
  keycloak_password:
    file: keycloak_password.txt